### ISSUE TITLE
Link warning (ld: warning: directory not found) on Mac OS

### ISSUE THREAD

**Issue by meoblast001** [jakubfijalkowski/hlibsass#5] opened 2016-11-09 23:59 UTC
As found in meoblast001/hakyll-sass#3, Mac OS users appear to be receiving the following link-time warning:

    ld: warning: directory not found for option '-L/private/var/folders/77/zxlvnwsj3dv3nc6kt_szls2w0000gn/T/cabal-tmp-5380/hlibsass-0.1.5.0/libsass/lib'

**Comment by jakubfijalkowski** [comment] 2016-11-13 12:14
Thanks for reporting!

I must have messed with linker paths too much ([here](https://github.com/jakubfijalkowski/hlibsass/blob/master/Setup.hs#L41-L58), if anyone is interested). I don't have the ability to test it on macOS for now, but I'll probably be able to do it in the coming month.

Do you know if this warning makes `hlibsass` unusable on macOS or does it have no effect?

**Comment by meoblast001** [comment] 2016-11-13 21:54
Sadly I cannot test this myself because I do not have macOS. This came as a bug report on one of my libraries. @turboMaCk was able to confirm this issue in my library and can perhaps let you know if this caused any functionality problems.

**Comment by turboMaCk** [comment] 2016-11-14 13:00
Hello.
I haven't noticed any issue while using hlibsass on Mac OS (10.12.1). I'm also free to help to investigate this.

**Comment by jakubfijalkowski** [comment] 2016-12-18 15:04
Hello once again. Sorry for the (really long) delay.

I've finally been able to work on this issue - the problem lies in the `updateExtraLibDirs` in `Setup.hs` - Cabal stores the generated path (and other `extra-lib-dirs`) in `.conf` file in the GHC's packages directory, but it points to `tmp` directory and gets deleted right after the package is installed. The fun thing is - the problem exists on every system, but only macOS version of `ld` prints the warning.

I've tried to tweak `Setup.hs` so that it does not set `extraLibDirs` but still specify correct library path for `ld`, but I failed (`configure` works, but `BuildInfo::ldOptions`/`BuildInfo::options` is ignored when linking).

I leave it as-is for now.

**Comment by jakubfijalkowski** [comment] 2017-03-19 21:47
This should be fixed in `hlibsass` 0.1.5.2 and `hsass` 0.4.1. Could you check this on macOS (I don't have access to macOS for now)?

**Comment by jakubfijalkowski** [comment] 2017-03-22 00:07
Okay, I've confirmed that the warning does not occur anymore (the temp path is no longer added to the extra lib dirs). Closing.

**Comment by turboMaCk** [comment] 2017-04-02 13:54
Hello @jakubfijalkowski 👋 
sorry for late response I've been quite busy recently. I've tried to compile this lib on mac but I'm not that experienced in Haskell ecosystem and I've ran into some issue. Today I had some time and realized I've missed presence of `libsass` submodule within this repository 🤕 . After pulling submodule I was able to compile everything without any issue using stack.

If I understand this correctly issue happened in linking time so building this from source should be enough to confirm that issue is resolved, right? I can confirm `cabal build` runs smoothly on macOs 10.12.3. But I still have a warning from `ld `. This is full output in case you're interested:

```
❯❯❯ cabal build                                                                                                                                                                                                                                                 
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
make: Nothing to be done for `all'.
Configuring hlibsass-0.1.6.0...
Building hlibsass-0.1.6.0...
Preprocessing library hlibsass-0.1.6.0...
[1 of 7] Compiling Bindings.Libsass.Types ( Bindings/Libsass/Types.hs, dist/build/Bindings/Libsass/Types.o )
[2 of 7] Compiling Bindings.Libsass.Values ( Bindings/Libsass/Values.hs, dist/build/Bindings/Libsass/Values.o )
[3 of 7] Compiling Bindings.Libsass.Wrappers ( Bindings/Libsass/Wrappers.hs, dist/build/Bindings/Libsass/Wrappers.o )
[4 of 7] Compiling Bindings.Libsass.Functions ( Bindings/Libsass/Functions.hs, dist/build/Bindings/Libsass/Functions.o )
[5 of 7] Compiling Bindings.Libsass.Context ( Bindings/Libsass/Context.hs, dist/build/Bindings/Libsass/Context.o )
[6 of 7] Compiling Bindings.Libsass.Base ( Bindings/Libsass/Base.hs, dist/build/Bindings/Libsass/Base.o )
[7 of 7] Compiling Bindings.Libsass ( Bindings/Libsass.hs, dist/build/Bindings/Libsass.o )
ld: warning: directory not found for option '-L/Users/marek/.cabal/lib/x86_64-osx-ghc-8.0.2/hlibsass-0.1.6.0-9hHC1JuOV4iHxgsjeVNDbz'
```

I've tried to run tests as well - all passes.

cheers
Marek

**Comment by jakubfijalkowski** [comment] 2017-04-03 20:18
Hi @turboMaCk !

Thank you very much for tests! I've forgotten about the existence of `cabal-install` and that it should work with `cabal` too (I've really got used to `stack`, and I don't use Haskell that much). :) Will investigate this once again on the weekend or some time soon.

**Comment by dunnl** [comment] 2017-09-26 13:29
Not sure if this is related but... I'm also getting linking errors on OS X that I can't reproduce on Linux. My project is also a hakyll site using hakyll-sass. Ironically I have missing symbol errors like this
```
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/dunnl/.stack/snapshots/x86_64-osx/lts-9.5/8.0.2/lib/x86_64-osx-ghc-8.0.2/hlibsass-0.1.6.1-5YgnetLqItEKQRTonDV5HP/libsass.a: unknown symbol `___dso_handle'
ghc: Could not on-demand load symbol '__ZN4Sass10VectorizedINS_10SharedImplINS_15Simple_SelectorEEEE20adjust_after_pushingES3_'
```
and duplicate symbol errors like this:
```
GHC runtime linker: fatal error: I found a duplicate definition for symbol
   __ZN4Sass15Simple_SelectorC2ENS_11ParserStateENSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
whilst processing object file
   /Users/dunnl/.stack/snapshots/x86_64-osx/lts-9.5/8.0.2/lib/x86_64-osx-ghc-8.0.2/hlibsass-0.1.6.1-5YgnetLqItEKQRTonDV5HP/libsass.a
The symbol was previously defined in
   /Users/dunnl/.stack/snapshots/x86_64-osx/lts-9.5/8.0.2/lib/x86_64-osx-ghc-8.0.2/hlibsass-0.1.6.1-5YgnetLqItEKQRTonDV5HP/libsass.a(node.o)
This could be caused by:
   * Loading two different object files which export the same symbol
   * Specifying the same object file twice on the GHCi command line
   * An incorrect `package.conf' entry, causing some object to be
     loaded twice.
```
I've tried nuking `.stack-work/` and even `~/.stack/snapshots/x86_64-osx/lts-9.5/` (and `lts-9.6`) but no luck. `stack.yaml` is pointing to lts-9.6 and a specific git commit of hakyll-sass [here](https://github.com/stoltene2/hakyll-sass/tree/master), but fiddling with the configuration doesn't make the problem go away.

Does my issue sound related to this one? I **am** able to build the master branch of hlibsass with stack without warnings.

**Comment by dunnl** [comment] 2017-09-26 15:34
I've traced my issue to a TemplateHaskell expression in an unrelated module. I've opened an issue on the other project [here](https://github.com/agrafix/elm-bridge/issues/20) if anyone is interested.

**Comment by jakubfijalkowski** [comment] 2017-09-26 17:23
Hey @dunnl,

Thank you for the report and the investigation! I think it is related to issue #1 and not this one. Nonetheless, it's good to know that this might not be related to `hlibsass`.

**Comment by jakubfijalkowski** [comment] 2020-03-26 17:20
Closing since there wasn't any activity recently (and the issue seems to be fixed).

**Closed as completed by jakubfijalkowski** 2020-03-26 17:20 UTC
